TARGET_LIB_SRC=libsrc.a

#INCLUDE_DIRS = /home/storm/env/basic/opencv/include

#LIBRARY_DIRS = /home/storm/env/basic/opencv/lib

#LIBS = opencv_core opencv_highgui opencv_imgproc opencv_imgcodecs

#CFLAGS = 
